// src/App.jsx
import { useEffect, useState, useRef } from "react";

import { IndexPage } from "./IndexPage";
import { Boutique } from "./boutique";
import { Lucena } from "./colecciones/lucena";
import { ElegancePro } from "./colecciones/elegance-pro";
import { Elysian } from "./colecciones/elysian";
import { SinaiCoem } from "./colecciones/sinai-coem";
import { SinaiKtl } from "./colecciones/sinai-ktl";
import { Glocal } from "./colecciones/glocal";
import { Materia } from "./colecciones/materia";
import { Sheer } from "./colecciones/sheer";
import { Motley } from "./colecciones/motley";
import { Supreme } from "./colecciones/supreme";
import { ImperialStone } from "./colecciones/imperial-stone";
import { Sybil } from "./colecciones/sybil";
import { Pulpis } from "./colecciones/pulpis";
import { PierreVive } from "./colecciones/pierre-vive";
import { Riverside } from "./colecciones/riverside";
import { Palermo } from "./colecciones/palermo";
import { Mapierre } from "./colecciones/mapierre";
import { Kora } from "./colecciones/kora";
import { Arenaria } from "./colecciones/arenaria";
import { Barcelona } from "./colecciones/barcelona";
import { OhTakeMountain } from "./colecciones/oh-take-mountain";
import { Portland } from "./colecciones/portland";
import { Chicago } from "./colecciones/chicago";
import { Icon } from "./colecciones/icon";
import { Bellevue } from "./colecciones/bellevue";
import { Ulisse } from "./colecciones/ulisse";
import { Dripart } from "./colecciones/dripart";
import { Oxyd } from "./colecciones/oxyd";
import { Bela } from "./colecciones/bela";
import { Kaizen } from "./colecciones/kaizen";
import { Retina } from "./colecciones/retina";
import { Jatoba } from "./colecciones/jatoba";
import { Verbier } from "./colecciones/verbier";
import { MoonCream } from "./colecciones/moon-cream";
import { Ribera } from "./colecciones/ribera";
import { Erawan } from "./colecciones/erawan";
import { Majestic } from "./colecciones/majestic";
import { Jurupa } from "./colecciones/jurupa";
import { TheRoom } from "./colecciones/the-room";
import { Bloom } from "./colecciones/bloom";
import { GlimGemme } from "./colecciones/glim-gemme";
import { Oxide } from "./colecciones/oxide";
import { WoodFog } from "./colecciones/wood-fog";
import { Unique } from "./colecciones/unique";
import { BlueRoma } from "./colecciones/blue-roma";
import { CanelaRoma } from "./colecciones/canela-roma";
import { Nordic } from "./colecciones/nordic";
import { FormCement } from "./colecciones/form-cement";
import { Mycro } from "./colecciones/mycro";
import { Coralina } from "./colecciones/coralina";
import { Caementum } from "./colecciones/caementum";
import { Papier } from "./colecciones/papier";
import { Jewels } from "./colecciones/jewels";
import { EnglishStone } from "./colecciones/english-stone";
import { TajMahal } from "./colecciones/taj-mahal";
import { TweedStone } from "./colecciones/tweed-stone";
import { Tivoli } from "./colecciones/tivoli";
import { Seine } from "./colecciones/seine";
import { Sandstone } from "./colecciones/sandstone";
import { Memory } from "./colecciones/memory";
import { NatureMood } from "./colecciones/nature-mood";
import { GreenTrees } from "./colecciones/green-trees";
import { TropicalBlue } from "./colecciones/tropical-blue";
import { MateriaClassica } from "./colecciones/materia-classica";
import { Borneo } from "./colecciones/borneo";
import { Borealis } from "./colecciones/borealis";
import { Arte } from "./colecciones/arte";
import { Dual } from "./colecciones/dual";
import { Mainstone } from "./colecciones/mainstone";
import { Praline } from "./colecciones/praline";
import { Sublime } from "./colecciones/sublime";
import { Hope } from "./colecciones/hope";
import { Cruise } from "./colecciones/cruise";
import { PietraEssenza } from "./colecciones/pietra-essenza";
import { DualTravertine } from "./colecciones/dual-travertine";
import { MateraStone } from "./colecciones/matera-stone";
import { Avallon } from "./colecciones/avallon";
import { Baikal } from "./colecciones/baikal";
import { Savoy } from "./colecciones/savoy";
import { Dot } from "./colecciones/dot";
import { Dhara } from "./colecciones/dhara";
import { Oregon } from "./colecciones/oregon";
import { Halton } from "./colecciones/halton";
import { Gulhi } from "./colecciones/gulhi";
import { Calizia } from "./colecciones/calizia";
import { Hauteville } from "./colecciones/hauteville";
import { Vinci } from "./colecciones/vinci";
import { Cement } from "./colecciones/cement";
import { Emotion } from "./colecciones/emotion";
import { FluidMulticolor } from "./colecciones/fluid-multicolor";
import { Tattoo } from "./colecciones/tattoo";
import { Cassero } from "./colecciones/cassero";
import { Cosmopolitan } from "./colecciones/cosmopolitan";
import { Artic } from "./colecciones/artic";
import { Arken } from "./colecciones/arken";
import { CuarzoReno } from "./colecciones/cuarzo-reno";
import { Distrito } from "./colecciones/distrito";
import { Incisa } from "./colecciones/incisa";
import { Onix } from "./colecciones/onix";
import { Silverline } from "./colecciones/silverline";
import { Civic } from "./colecciones/civic";
import { Blanco } from "./colecciones/blanco";
import { Cottage } from "./colecciones/cottage";
import { Duomo } from "./colecciones/duomo";
import { LuminaStone } from "./colecciones/lumina-stone";
import { Micra } from "./colecciones/micra";
import { Mitica } from "./colecciones/mitica";
import { Oxo } from "./colecciones/oxo";
import { Surface } from "./colecciones/surface";
import { Dust } from "./colecciones/dust";
import { Beck } from "./colecciones/beck";
import { Brutalist } from "./colecciones/brutalist";
import { LongStick } from "./colecciones/long-stick";
import { Alma } from "./colecciones/alma";
import { Alure } from "./colecciones/alure";
import { Glint } from "./colecciones/glint";
import { Argila } from "./colecciones/argila";
import { Joy } from "./colecciones/joy";
import { Provenza } from "./colecciones/provenza";
import { Riad4x4 } from "./colecciones/riad-4x4";
import { Zelij4x4 } from "./colecciones/zelij-4x4";
import { ZelijMate4x4 } from "./colecciones/zelij-mate-4x4";
import { ZelijSpecial4x4 } from "./colecciones/zelij-special-4x4";
import { Andrassy } from "./colecciones/andrassy";
import { Beltri } from "./colecciones/beltri";
import { Blomknopp } from "./colecciones/blomknopp";
import { Bucareli } from "./colecciones/bucareli";
import { Bulnes } from "./colecciones/bulnes";
import { Cestio } from "./colecciones/cestio";
import { Comillas } from "./colecciones/comillas";
import { Creta } from "./colecciones/creta";
import { Eliseos } from "./colecciones/eliseos";
import { Florentina } from "./colecciones/florentina";
import { Gibert } from "./colecciones/gibert";
import { Goroka } from "./colecciones/goroka";
import { Northon } from "./colecciones/northon";
import { Doncella } from "./colecciones/doncella";
import { Crisp } from "./colecciones/crisp";
import { DecoArt } from "./colecciones/deco-art";
import { Flax } from "./colecciones/flax";
import { Intermix } from "./colecciones/intermix";
import { Jimbaran } from "./colecciones/jimbaran";
import { Jujol } from "./colecciones/jujol";
import { Linden } from "./colecciones/linden";
import { Llagostera } from "./colecciones/llagostera";
import { Lighthouse } from "./colecciones/lighthouse";
import { Macaya } from "./colecciones/macaya";
import { Norvins } from "./colecciones/norvins";
import { Nusa } from "./colecciones/nusa";
import { Orchard } from "./colecciones/orchard";
import { OrganicClay } from "./colecciones/organic-clay";
import { Palau } from "./colecciones/palau";
import { Suanzes } from "./colecciones/suanzes";
import { Terralma } from "./colecciones/terralma";
import { Tuban } from "./colecciones/tuban";
import { Tulban } from "./colecciones/tulban";
import { Ubud } from "./colecciones/ubud";
import { Valvanera } from "./colecciones/valvanera";
import { Vivant } from "./colecciones/vivant";
import { Tears } from "./colecciones/tears";
import { Terre } from "./colecciones/terre";
import { TrameDiPietra } from "./colecciones/trame-di-pietra";
import { Blaze } from "./colecciones/blaze";
import { Sahn4x4 } from "./colecciones/sahn-4x4";
import { Zellige } from "./colecciones/zellige";
import { Bethel } from "./colecciones/bethel";
import { Bonnie } from "./colecciones/bonnie";
import { Carnegie } from "./colecciones/carnegie";
import { Cavern } from "./colecciones/cavern";
import { Ferus } from "./colecciones/ferus";
import { Fluxus } from "./colecciones/fluxus";
import { HisbalitMosaico } from "./colecciones/hisbalit-mosaico";
import { Marquee } from "./colecciones/marquee";
import { Popart } from "./colecciones/popart";
import { Saville } from "./colecciones/saville";
import { Sixties } from "./colecciones/sixties";
import { Quecto } from "./colecciones/quecto";
import { Zepto } from "./colecciones/zepto";
import { ZelijGlossy2x8 } from "./colecciones/zelij-glossy-2x8";
import { ZelijMate2x8 } from "./colecciones/zelij-mate-2x8";
import { ZelijSpecial2x8 } from "./colecciones/zelij-special-2x8";
import { Lagoon } from "./colecciones/lagoon";
import { Land } from "./colecciones/land";
import { Legacy3x10 } from "./colecciones/legacy-3x10";
import { Rabat } from "./colecciones/rabat";
import { Rustic } from "./colecciones/rustic";
import { Jazba } from "./colecciones/jazba";
import { Glow } from "./colecciones/glow";
import { AlaskaCevica } from "./colecciones/alaska-cevica";
import { BaliCerlat } from "./colecciones/bali-cerlat";
import { Gouache } from "./colecciones/gouache";
import { Habana } from "./colecciones/habana";
import { Legacy6x6 } from "./colecciones/legacy-6x6";
import { Nexus } from "./colecciones/nexus";
import { Dyroy3x8 } from "./colecciones/dyroy-3x8";
import { Dyroy4x4 } from "./colecciones/dyroy-4x4";
import { Sahn3x8 } from "./colecciones/sahn-3x8";
import { Industrial } from "./colecciones/industrial";
import { Bari } from "./colecciones/bari";
import { Scale } from "./colecciones/scale";


export function App() {
  const [page, setPage] = useState("home");
  const touchStartX = useRef(0);
  const touchStartY = useRef(0);
  const trackingSwipe = useRef(false);

  useEffect(() => {
    function handleGlobalGoHome() {
      setPage("home");
    }

    function handleGlobalGoBoutique() {
      setPage("boutique");
    }

    function handleTouchStart(e) {
      if (window.innerWidth > 1024) return;
      if (e.touches.length !== 1) return;

      const touch = e.touches[0];

      if (touch.clientX <= 30) {
        trackingSwipe.current = true;
        touchStartX.current = touch.clientX;
        touchStartY.current = touch.clientY;
      } else {
        trackingSwipe.current = false;
      }
    }

    function handleTouchEnd(e) {
      if (window.innerWidth > 1024) return;
      if (!trackingSwipe.current) return;

      const touch = e.changedTouches[0];
      const deltaX = touch.clientX - touchStartX.current;
      const deltaY = Math.abs(touch.clientY - touchStartY.current);

      if (deltaX > 80 && deltaY < 80) {
        setPage("home");
      }

      trackingSwipe.current = false;
    }

    window.addEventListener("go-home", handleGlobalGoHome);
    window.addEventListener("go-boutique", handleGlobalGoBoutique);
    window.addEventListener("touchstart", handleTouchStart, { passive: true });
    window.addEventListener("touchend", handleTouchEnd, { passive: true });

    return () => {
      window.removeEventListener("go-home", handleGlobalGoHome);
      window.removeEventListener("go-boutique", handleGlobalGoBoutique);
      window.removeEventListener("touchstart", handleTouchStart);
      window.removeEventListener("touchend", handleTouchEnd);
    };
  }, []);

  function handleOpenCollection(name) {
    if (name === "BOUTIQUE") setPage("boutique");
    if (name === "DUST") setPage("dust");
    if (name === "LUCENA") setPage("lucena");
    if (name === "ELEGANCE PRO") setPage("elegance-pro");
    if (name === "ELYSIAN") setPage("elysian");
    if (name === "SINAI COEM") setPage("sinai-coem");
    if (name === "SINAI KTL") setPage("sinai-ktl");
    if (name === "GLOCAL") setPage("glocal");
    if (name === "MATERIA") setPage("materia");
    if (name === "MOTLEY") setPage("motley");
    if (name === "SHEER") setPage("sheer");
    if (name === "SUPREME") setPage("supreme");
    if (name === "IMPERIAL STONE") setPage("imperial-stone");
    if (name === "SYBIL") setPage("sybil");
    if (name === "PULPIS") setPage("pulpis");
    if (name === "PIERRE VIVE") setPage("pierre-vive");
    if (name === "RIVERSIDE") setPage("riverside");
    if (name === "PALERMO") setPage("palermo");
    if (name === "MAPIERRE") setPage("mapierre");
    if (name === "KORA") setPage("kora");
    if (name === "ARENARIA") setPage("arenaria");
    if (name === "BARCELONA") setPage("barcelona");
    if (name === "OH TAKE MOUNTAIN") setPage("oh-take-mountain");
    if (name === "PORTLAND") setPage("portland");
    if (name === "CHICAGO") setPage("chicago");
    if (name === "ICON") setPage("icon");
    if (name === "BELLEVUE") setPage("bellevue");
    if (name === "ULISSE") setPage("ulisse");
    if (name === "DRIPART") setPage("dripart");
    if (name === "OXYD") setPage("oxyd");
    if (name === "BELA") setPage("bela");
    if (name === "KAIZEN") setPage("kaizen");
    if (name === "RETINA") setPage("retina");
    if (name === "JATOBA") setPage("jatoba");
    if (name === "VERBIER") setPage("verbier");
    if (name === "MOON CREAM") setPage("moon-cream");
    if (name === "RIBERA") setPage("ribera");
    if (name === "ERAWAN") setPage("erawan");
    if (name === "MAJESTIC") setPage("majestic");
    if (name === "JURUPA") setPage("jurupa");
    if (name === "THE ROOM") setPage("the-room");
    if (name === "BLOOM") setPage("bloom");
    if (name === "GLIM GEMME") setPage("glim-gemme");
    if (name === "OXIDE") setPage("oxide");
    if (name === "WOOD FOG") setPage("wood-fog");
    if (name === "UNIQUE") setPage("unique");
    if (name === "BLUE ROMA") setPage("blue-roma");
    if (name === "CANELA ROMA") setPage("canela-roma");
    if (name === "NORDIC") setPage("nordic");
    if (name === "FORM CEMENT") setPage("form-cement");
    if (name === "MYCRO") setPage("mycro");
    if (name === "CORALINA") setPage("coralina");
    if (name === "CAEMENTUM") setPage("caementum");
    if (name === "PAPIER") setPage("papier");
    if (name === "JEWELS") setPage("jewels");
    if (name === "ENGLISH STONE") setPage("english-stone");
    if (name === "TAJ MAHAL") setPage("taj-mahal");
    if (name === "TWEED STONE") setPage("tweed-stone");
    if (name === "TIVOLI") setPage("tivoli");
    if (name === "SEINE") setPage("seine");
    if (name === "SANDSTONE") setPage("sandstone");
    if (name === "MEMORY") setPage("memory");
    if (name === "NATURE MOOD") setPage("nature-mood");
    if (name === "GREEN TREES") setPage("green-trees");
    if (name === "TROPICAL BLUE") setPage("tropical-blue");
    if (name === "MATERIA CLASSICA") setPage("materia-classica");
    if (name === "BORNEO") setPage("borneo");
    if (name === "BOREALIS") setPage("borealis");
    if (name === "ARTE") setPage("arte");
    if (name === "DUAL") setPage("dual");
    if (name === "MAINSTONE") setPage("mainstone");
    if (name === "PRALINE") setPage("praline");
    if (name === "SUBLIME") setPage("sublime");
    if (name === "HOPE") setPage("hope");
    if (name === "CRUISE") setPage("cruise");
    if (name === "PIETRA ESSENZA") setPage("pietra-essenza");
    if (name === "DUAL TRAVERTINE") setPage("dual-travertine");
    if (name === "MATERA STONE") setPage("matera-stone");
    if (name === "AVALLON") setPage("avallon");
    if (name === "BAIKAL") setPage("baikal");
    if (name === "SAVOY") setPage("savoy");
    if (name === "DOT") setPage("dot");
    if (name === "DHARA") setPage("dhara");
    if (name === "OREGON") setPage("oregon");
    if (name === "HALTON") setPage("halton");
    if (name === "GULHI") setPage("gulhi");
    if (name === "CALIZIA") setPage("calizia");
    if (name === "HAUTEVILLE") setPage("hauteville");
    if (name === "VINCI") setPage("vinci");
    if (name === "CEMENT") setPage("cement");
    if (name === "EMOTION") setPage("emotion");
    if (name === "FLUID MULTICOLOR") setPage("fluid-multicolor");
    if (name === "TATTOO") setPage("tattoo");
    if (name === "CASSERO") setPage("cassero");
    if (name === "COSMOPOLITAN") setPage("cosmopolitan");
    if (name === "ARTIC") setPage("artic");
    if (name === "ARKEN") setPage("arken");
    if (name === "CUARZO RENO") setPage("cuarzo-reno");
    if (name === "DISTRITO") setPage("distrito");
    if (name === "INCISA") setPage("incisa");
    if (name === "ONIX") setPage("onix");
    if (name === "SILVERLINE") setPage("silverline");
    if (name === "CIVIC") setPage("civic");
    if (name === "BLANCO") setPage("blanco");
    if (name === "COTTAGE") setPage("cottage");
    if (name === "DUOMO") setPage("duomo");
    if (name === "LUMINA STONE") setPage("lumina-stone");
    if (name === "MICRA") setPage("micra");
    if (name === "MITICA") setPage("mitica");
    if (name === "OXO") setPage("oxo");
    if (name === "SURFACE") setPage("surface");
    if (name === "BECK") setPage("beck");
    if (name === "BRUTALIST") setPage("brutalist");
    if (name === "LONG STICK") setPage("long-stick");
    if (name === "ALMA") setPage("alma");
    if (name === "ALURE") setPage("alure");
    if (name === "GLINT") setPage("glint");
    if (name === "ARGILA") setPage("argila");
    if (name === "JOY") setPage("joy");
    if (name === "PROVENZA") setPage("provenza");
    if (name === "RIAD") setPage("riad-4x4");
    if (name === "ZELIJ") setPage("zelij-4x4");
    if (name === "ZELIJ MATE") setPage("zelij-mate-4x4");
    if (name === "ZELIJ SPECIAL") setPage("zelij-special-4x4");
    if (name === "ANDRASSY") setPage("andrassy");
    if (name === "BELTRI") setPage("beltri");
    if (name === "BLOMKNOPP") setPage("blomknopp");
    if (name === "BUCARELI") setPage("bucareli");
    if (name === "BULNES") setPage("bulnes");
    if (name === "CESTIO") setPage("cestio");
    if (name === "COMILLAS") setPage("comillas");
    if (name === "CRETA") setPage("creta");
    if (name === "ELISEOS") setPage("eliseos");
    if (name === "FLORENTINA") setPage("florentina");
    if (name === "GIBERT") setPage("gibert");
    if (name === "GOROKA") setPage("goroka");
    if (name === "NORTHON") setPage("northon");
    if (name === "DONCELLA") setPage("doncella");
    if (name === "CRISP") setPage("crisp");
    if (name === "DECO ART") setPage("deco-art");
    if (name === "FLAX") setPage("flax");
    if (name === "INTERMIX") setPage("intermix");
    if (name === "JIMBARAN") setPage("jimbaran");
    if (name === "JUJOL") setPage("jujol");
    if (name === "LINDEN") setPage("linden");
    if (name === "LLAGOSTERA") setPage("llagostera");
    if (name === "LIGHTHOUSE") setPage("lighthouse");
    if (name === "MACAYA") setPage("macaya");
    if (name === "NORVINS") setPage("norvins");
    if (name === "NUSA") setPage("nusa");
    if (name === "ORCHARD") setPage("orchard");
    if (name === "ORGANIC CLAY") setPage("organic-clay");
    if (name === "PALAU") setPage("palau");
    if (name === "SUANZES") setPage("suanzes");
    if (name === "TERRALMA") setPage("terralma");
    if (name === "TUBAN") setPage("tuban");
    if (name === "TULBAN") setPage("tulban");
    if (name === "UBUD") setPage("ubud");
    if (name === "VALVANERA") setPage("valvanera");
    if (name === "VIVANT") setPage("vivant");
    if (name === "TEARS") setPage("tears");
    if (name === "TERRE") setPage("terre");
    if (name === "TRAME DI PIETRA") setPage("trame-di-pietra");
    if (name === "BLAZE") setPage("blaze");
    if (name === "SAHN") setPage("sahn-4x4");
    if (name === "ZELLIGE") setPage("zellige");
    if (name === "BETHEL") setPage("bethel");
    if (name === "BONNIE") setPage("bonnie");
    if (name === "CARNEGIE") setPage("carnegie");
    if (name === "CAVERN") setPage("cavern");
    if (name === "FERUS") setPage("ferus");
    if (name === "FLUXUS") setPage("fluxus");
    if (name === "HISBALIT MOSAICO") setPage("hisbalit-mosaico");
    if (name === "MARQUEE") setPage("marquee");
    if (name === "POPART") setPage("popart");
    if (name === "SAVILLE") setPage("saville");
    if (name === "SIXTIES") setPage("sixties");
    if (name === "QUECTO") setPage("quecto");
    if (name === "ZEPTO") setPage("zepto");
    if (name === "ZELIJ GLOSSY 2x8") setPage("zelij-glossy-2x8");
    if (name === "ZELIJ MATE 2x8") setPage("zelij-mate-2x8");
    if (name === "ZELIJ SPECIAL 2x8") setPage("zelij-special-2x8");
    if (name === "LAGOON") setPage("lagoon");
    if (name === "LAND") setPage("land");
    if (name === "LEGACY 3X10") setPage("legacy-3x10");
    if (name === "RABAT") setPage("rabat");
    if (name === "RUSTIC") setPage("rustic");
    if (name === "JAZBA") setPage("jazba");
    if (name === "GLOW") setPage("glow");
    if (name === "ALASKA CEVICA") setPage("alaska-cevica");
    if (name === "BALI CERLAT") setPage("bali-cerlat");
    if (name === "GOUACHE") setPage("gouache");
    if (name === "HABANA") setPage("habana");
    if (name === "LEGACY 6X6") setPage("legacy-6x6");
    if (name === "NEXUS") setPage("nexus");
    if (name === "DYROY 3X8") setPage("dyroy-3x8");
    if (name === "DYROY 4X4") setPage("dyroy-4x4");
    if (name === "SAHN 3X8") setPage("sahn-3x8");
    if (name === "INDUSTRIAL") setPage("industrial");
    if (name === "BARI") setPage("bari");
    if (name === "SCALE") setPage("scale");
  }

  if (page === "home") {
    return <IndexPage onOpenCollection={handleOpenCollection} />;
  }

  if (page === "boutique") {
    return <Boutique onOpenCollection={handleOpenCollection} />;
  }

  if (page === "lucena") return <Lucena />;
  if (page === "dust") return <Dust />;
  if (page === "elegance-pro") return <ElegancePro />;
  if (page === "elysian") return <Elysian />;
  if (page === "sinai-coem") return <SinaiCoem />;
  if (page === "sinai-ktl") return <SinaiKtl />;
  if (page === "glocal") return <Glocal />;
  if (page === "materia") return <Materia />;
  if (page === "sheer") return <Sheer />;
  if (page === "motley") return <Motley />;
  if (page === "supreme") return <Supreme />;
  if (page === "imperial-stone") return <ImperialStone />;
  if (page === "sybil") return <Sybil />;
  if (page === "pulpis") return <Pulpis />;
  if (page === "pierre-vive") return <PierreVive />;
  if (page === "riverside") return <Riverside />;
  if (page === "palermo") return <Palermo />;
  if (page === "mapierre") return <Mapierre />;
  if (page === "kora") return <Kora />;
  if (page === "arenaria") return <Arenaria />;
  if (page === "barcelona") return <Barcelona />;
  if (page === "oh-take-mountain") return <OhTakeMountain />;
  if (page === "portland") return <Portland />;
  if (page === "chicago") return <Chicago />;
  if (page === "icon") return <Icon />;
  if (page === "bellevue") return <Bellevue />;
  if (page === "ulisse") return <Ulisse />;
  if (page === "dripart") return <Dripart />;
  if (page === "oxyd") return <Oxyd />;
  if (page === "bela") return <Bela />;
  if (page === "kaizen") return <Kaizen />;
  if (page === "retina") return <Retina />;
  if (page === "jatoba") return <Jatoba />;
  if (page === "verbier") return <Verbier />;
  if (page === "moon-cream") return <MoonCream />;
  if (page === "ribera") return <Ribera />;
  if (page === "erawan") return <Erawan />;
  if (page === "majestic") return <Majestic />;
  if (page === "jurupa") return <Jurupa />;
  if (page === "the-room") return <TheRoom />;
  if (page === "bloom") return <Bloom />;
  if (page === "glim-gemme") return <GlimGemme />;
  if (page === "oxide") return <Oxide />;
  if (page === "wood-fog") return <WoodFog />;
  if (page === "unique") return <Unique />;
  if (page === "blue-roma") return <BlueRoma />;
  if (page === "canela-roma") return <CanelaRoma />;
  if (page === "nordic") return <Nordic />;
  if (page === "form-cement") return <FormCement />;
  if (page === "mycro") return <Mycro />;
  if (page === "coralina") return <Coralina />;
  if (page === "caementum") return <Caementum />;
  if (page === "papier") return <Papier />;
  if (page === "jewels") return <Jewels />;
  if (page === "english-stone") return <EnglishStone />;
  if (page === "taj-mahal") return <TajMahal />;
  if (page === "tweed-stone") return <TweedStone />;
  if (page === "tivoli") return <Tivoli />;
  if (page === "seine") return <Seine />;
  if (page === "sandstone") return <Sandstone />;
  if (page === "memory") return <Memory />;
  if (page === "nature-mood") return <NatureMood />;
  if (page === "green-trees") return <GreenTrees />;
  if (page === "tropical-blue") return <TropicalBlue />;
  if (page === "materia-classica") return <MateriaClassica />;
  if (page === "borneo") return <Borneo />;
  if (page === "borealis") return <Borealis />;
  if (page === "arte") return <Arte />;
  if (page === "dual") return <Dual />;
  if (page === "mainstone") return <Mainstone />;
  if (page === "praline") return <Praline />;
  if (page === "sublime") return <Sublime />;
  if (page === "hope") return <Hope />;
  if (page === "cruise") return <Cruise />;
  if (page === "pietra-essenza") return <PietraEssenza />;
  if (page === "dual-travertine") return <DualTravertine />;
  if (page === "matera-stone") return <MateraStone />;
  if (page === "avallon") return <Avallon />;
  if (page === "baikal") return <Baikal />;
  if (page === "savoy") return <Savoy />;
  if (page === "dot") return <Dot />;
  if (page === "dhara") return <Dhara />;
  if (page === "oregon") return <Oregon />;
  if (page === "halton") return <Halton />;
  if (page === "gulhi") return <Gulhi />;
  if (page === "calizia") return <Calizia />;
  if (page === "hauteville") return <Hauteville />;
  if (page === "vinci") return <Vinci />;
  if (page === "cement") return <Cement />;
  if (page === "emotion") return <Emotion />;
  if (page === "fluid-multicolor") return <FluidMulticolor />;
  if (page === "tattoo") return <Tattoo />;
  if (page === "cassero") return <Cassero />;
  if (page === "cosmopolitan") return <Cosmopolitan />;
  if (page === "artic") return <Artic />;
  if (page === "arken") return <Arken />;
  if (page === "cuarzo-reno") return <CuarzoReno />;
  if (page === "distrito") return <Distrito />;
  if (page === "incisa") return <Incisa />;
  if (page === "onix") return <Onix />;
  if (page === "silverline") return <Silverline />;
  if (page === "civic") return <Civic />;
  if (page === "blanco") return <Blanco />;
  if (page === "cottage") return <Cottage />;
  if (page === "duomo") return <Duomo />;
  if (page === "lumina-stone") return <LuminaStone />;
  if (page === "micra") return <Micra />;
  if (page === "mitica") return <Mitica />;
  if (page === "oxo") return <Oxo />;
  if (page === "surface") return <Surface />;
  if (page === "beck") return <Beck />;
  if (page === "brutalist") return <Brutalist />;
  if (page === "long-stick") return <LongStick />;
  if (page === "alma") return <Alma />;
  if (page === "alure") return <Alure />;
  if (page === "glint") return <Glint />;
  if (page === "argila") return <Argila />;
  if (page === "joy") return <Joy />;
  if (page === "provenza") return <Provenza />;
  if (page === "riad-4x4") return <Riad4x4 />;
  if (page === "zelij-4x4") return <Zelij4x4 />;
  if (page === "zelij-mate-4x4") return <ZelijMate4x4 />;
  if (page === "zelij-special-4x4") return <ZelijSpecial4x4 />;
  if (page === "andrassy") return <Andrassy />;
  if (page === "beltri") return <Beltri />;
  if (page === "blomknopp") return <Blomknopp />;
  if (page === "bucareli") return <Bucareli />;
  if (page === "bulnes") return <Bulnes />;
  if (page === "cestio") return <Cestio />;
  if (page === "comillas") return <Comillas />;
  if (page === "creta") return <Creta />;
  if (page === "eliseos") return <Eliseos />;
  if (page === "florentina") return <Florentina />;
  if (page === "gibert") return <Gibert />;
  if (page === "goroka") return <Goroka />;
  if (page === "northon") return <Northon />;
  if (page === "doncella") return <Doncella />;
  if (page === "crisp") return <Crisp />;
  if (page === "deco-art") return <DecoArt />;
  if (page === "flax") return <Flax />;
  if (page === "intermix") return <Intermix />;
  if (page === "jimbaran") return <Jimbaran />;
  if (page === "jujol") return <Jujol />;
  if (page === "linden") return <Linden />;
  if (page === "llagostera") return <Llagostera />;
  if (page === "lighthouse") return <Lighthouse />;
  if (page === "macaya") return <Macaya />;
  if (page === "norvins") return <Norvins />;
  if (page === "nusa") return <Nusa />;
  if (page === "orchard") return <Orchard />;
  if (page === "organic-clay") return <OrganicClay />;
  if (page === "palau") return <Palau />;
  if (page === "suanzes") return <Suanzes />;
  if (page === "terralma") return <Terralma />;
  if (page === "tuban") return <Tuban />;
  if (page === "tulban") return <Tulban />;
  if (page === "ubud") return <Ubud />;
  if (page === "valvanera") return <Valvanera />;
  if (page === "vivant") return <Vivant />;
  if (page === "tears") return <Tears />;
  if (page === "terre") return <Terre />;
  if (page === "trame-di-pietra") return <TrameDiPietra />;
  if (page === "blaze") return <Blaze />;
  if (page === "sahn-4x4") return <Sahn4x4 />;
  if (page === "zellige") return <Zellige />;
  if (page === "bethel") return <Bethel />;
  if (page === "bonnie") return <Bonnie />;
  if (page === "carnegie") return <Carnegie />;
  if (page === "cavern") return <Cavern />;
  if (page === "ferus") return <Ferus />;
  if (page === "fluxus") return <Fluxus />;
  if (page === "hisbalit-mosaico") return <HisbalitMosaico />;
  if (page === "marquee") return <Marquee />;
  if (page === "popart") return <Popart />;
  if (page === "saville") return <Saville />;
  if (page === "sixties") return <Sixties />;
  if (page === "quecto") return <Quecto />;
  if (page === "zepto") return <Zepto />;
  if (page === "zelij-4x4") return <Zelij4x4 />;
  if (page === "zelij-mate-4x4") return <ZelijMate4x4 />;
  if (page === "zelij-special-4x4") return <ZelijSpecial4x4 />;
  if (page === "zelij-glossy-2x8") return <ZelijGlossy2x8 />;
  if (page === "zelij-mate-2x8") return <ZelijMate2x8 />;
  if (page === "zelij-special-2x8") return <ZelijSpecial2x8 />;
  if (page === "lagoon") return <Lagoon />;
  if (page === "land") return <Land />;
  if (page === "legacy-3x10") return <Legacy3x10 />;
  if (page === "rabat") return <Rabat />;
  if (page === "rustic") return <Rustic />;
  if (page === "jazba") return <Jazba />;
  if (page === "glow") return <Glow />;
  if (page === "alaska-cevica") return <AlaskaCevica />;
  if (page === "bali-cerlat") return <BaliCerlat />;
  if (page === "gouache") return <Gouache />;
  if (page === "habana") return <Habana />;
  if (page === "legacy-6x6") return <Legacy6x6 />;
  if (page === "nexus") return <Nexus />;
  if (page === "dyroy-3x8") return <Dyroy3x8 />;
  if (page === "dyroy-4x4") return <Dyroy4x4 />;
  if (page === "sahn-3x8") return <Sahn3x8 />;
  if (page === "industrial") return <Industrial />;
  if (page === "bari") return <Bari />;
  if (page === "scale") return <Scale />;
  


  return null;
}

export default App;
